use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    // Embed the build date/time as UTC. `BUILD_DATE` is the ISO date for the
    // window title; `BUILD_TIMESTAMP` is a full ISO 8601 / RFC 3339 instant
    // (e.g. `2026-07-03T14:30:00Z`) — chrono's `to_rfc3339_opts` gives the
    // standard form directly, no manual field assembly.
    let now = chrono::Utc::now();
    let date = now.format("%Y-%m-%d");
    let timestamp = now.to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
    println!("cargo:rustc-env=BUILD_DATE={date}");
    println!("cargo:rustc-env=BUILD_TIMESTAMP={timestamp}");

    embed_git_info();
    generate_font_registry();

    // Emitting rerun-if-changed disables cargo's default "any package file"
    // rerun, so re-add the package sources alongside the git triggers.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=src");
}

/// Scan `assets/fonts/` for bundled fonts and generate `BUNDLED_FONTS`, a
/// `&[(family_name, bytes)]` table embedded via `include_bytes!`. The font
/// picker in Settings is populated straight from this table, so dropping a new
/// `.ttf`/`.otf` into that directory and rebuilding makes it selectable — no
/// code change. Each entry's display name is the font's own family name (read
/// from its `name` table), falling back to the file stem.
fn generate_font_registry() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let fonts_rel = "assets/fonts";
    let fonts_dir = Path::new(&manifest_dir).join(fonts_rel);
    // Rebuild the generated table whenever the fonts directory changes.
    println!("cargo:rerun-if-changed={fonts_rel}");

    // Collect font files, sorted by path for a deterministic scan.
    let mut files: Vec<PathBuf> = std::fs::read_dir(&fonts_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", fonts_dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            p.extension()
                .and_then(|s| s.to_str())
                .is_some_and(|e| e.eq_ignore_ascii_case("ttf") || e.eq_ignore_ascii_case("otf"))
        })
        .collect();
    files.sort();

    // (family_name, absolute_path) — sorted by name for a stable picker order.
    let mut entries: Vec<(String, String)> = Vec::new();
    for path in &files {
        let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("Font")
            .to_string();
        let name = font_family_name(&bytes).unwrap_or(stem);
        // Forward slashes are accepted in include paths on every platform.
        let abs = path.to_string_lossy().replace('\\', "/");
        entries.push((name, abs));
    }
    entries.sort_by_key(|(name, _)| name.to_lowercase());

    let mut out = String::from("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static BUNDLED_FONTS: &[(&str, &[u8])] = &[\n");
    for (name, abs) in &entries {
        let esc_name = name.replace('\\', "\\\\").replace('"', "\\\"");
        let esc_path = abs.replace('\\', "\\\\").replace('"', "\\\"");
        out.push_str(&format!(
            "    (\"{esc_name}\", include_bytes!(\"{esc_path}\")),\n"
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("bundled_fonts.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

/// Read the human-readable family name from an sfnt (`.ttf`/`.otf`) `name`
/// table. Prefers the typographic family (nameID 16) over the legacy family
/// (nameID 1), and the Windows platform (UTF-16BE) over Macintosh (Latin-1).
/// Returns `None` for a malformed/absent table so the caller can fall back.
fn font_family_name(bytes: &[u8]) -> Option<String> {
    fn be_u16(b: &[u8], o: usize) -> Option<u16> {
        b.get(o..o + 2).map(|s| u16::from_be_bytes([s[0], s[1]]))
    }
    fn be_u32(b: &[u8], o: usize) -> Option<u32> {
        b.get(o..o + 4)
            .map(|s| u32::from_be_bytes([s[0], s[1], s[2], s[3]]))
    }

    let num_tables = be_u16(bytes, 4)? as usize;
    let mut name_table = None;
    for i in 0..num_tables {
        let rec = 12 + i * 16;
        if bytes.get(rec..rec + 4)? == b"name" {
            name_table = Some(be_u32(bytes, rec + 8)? as usize);
            break;
        }
    }
    let nt = name_table?;
    let count = be_u16(bytes, nt + 2)? as usize;
    let storage = nt + be_u16(bytes, nt + 4)? as usize;

    // Lower rank = more preferred.
    let rank = |pid: u16, nid: u16| -> Option<u8> {
        match (pid, nid) {
            (3, 16) => Some(0),
            (1, 16) => Some(1),
            (3, 1) => Some(2),
            (1, 1) => Some(3),
            _ => None,
        }
    };

    let mut best: Option<(u8, String)> = None;
    for i in 0..count {
        let r = nt + 6 + i * 12;
        let pid = be_u16(bytes, r)?;
        let nid = be_u16(bytes, r + 6)?;
        let len = be_u16(bytes, r + 8)? as usize;
        let off = be_u16(bytes, r + 10)? as usize;
        let Some(rk) = rank(pid, nid) else { continue };
        let raw = bytes.get(storage + off..storage + off + len)?;
        let text = if pid == 3 {
            let units: Vec<u16> = raw
                .as_chunks::<2>()
                .0
                .iter()
                .map(|c| u16::from_be_bytes([c[0], c[1]]))
                .collect();
            String::from_utf16(&units).ok()?
        } else {
            raw.iter().map(|&b| b as char).collect()
        };
        let text = text.trim().to_string();
        if text.is_empty() {
            continue;
        }
        let take = match &best {
            Some((brk, _)) => rk < *brk,
            None => true,
        };
        if take {
            best = Some((rk, text));
        }
    }
    best.map(|(_, t)| t)
}

/// Embed commit hash, branch, and working-tree dirtiness at build time.
/// All values fall back to empty strings when git (or the repo) is absent,
/// e.g. when building from a source tarball.
fn embed_git_info() {
    let hash = git(&["rev-parse", "HEAD"]);
    let branch = git(&["rev-parse", "--abbrev-ref", "HEAD"]);
    // "1" dirty, "0" clean, "" unknown (matches the hash/branch fallback)
    let dirty = match git_output(&["status", "--porcelain"]) {
        Some(out) => {
            if out.trim().is_empty() {
                "0"
            } else {
                "1"
            }
        }
        None => "",
    };
    println!("cargo:rustc-env=GIT_COMMIT_HASH={hash}");
    println!("cargo:rustc-env=GIT_BRANCH={branch}");
    println!("cargo:rustc-env=GIT_DIRTY={dirty}");

    // Rerun on commit / branch switch / staging so the embedded info tracks HEAD.
    if let Some(git_dir) = git_output(&["rev-parse", "--absolute-git-dir"]) {
        let git_dir = git_dir.trim();
        println!("cargo:rerun-if-changed={git_dir}/HEAD");
        println!("cargo:rerun-if-changed={git_dir}/index");
    }
}

fn git(args: &[&str]) -> String {
    git_output(args)
        .map(|s| s.trim().to_string())
        .unwrap_or_default()
}

fn git_output(args: &[&str]) -> Option<String> {
    let out = Command::new("git").args(args).output().ok()?;
    if !out.status.success() {
        return None;
    }
    String::from_utf8(out.stdout).ok()
}
