[package]
name = "synth_modules"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Synth modules and audio effects for Pertylizer"
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
synth_core = { path = "../synth_core" }
synth_dsp = { path = "../synth_dsp" }
synth_sampler = { path = "../synth_sampler" }
serde = { workspace = true }
fastrand = { workspace = true }
ringbuf = { workspace = true }
